<?php
// autogenerated file 09.05.2012 13:19
// $Id: $
// $Log: $
//
//
require_once 'MismatchTypeCodeType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Complex type that defines the <b>eBayPaymentMismatchDetails</b> container, 
 * whichis returned when a buyer's payment does not match the total cost of an 
 * order going throughthe new eBay payment process. This type is only applicable 
 * for German and Austrian orders goingthrough the new eBay payment process. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/eBayPaymentMismatchDetailsType.html
 *
 */
class eBayPaymentMismatchDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var MismatchTypeCodeType
	 */
	protected $MismatchType;
	/**
	 * @var dateTime
	 */
	protected $ActionRequiredBy;

	/**
	 * @return MismatchTypeCodeType
	 */
	function getMismatchType()
	{
		return $this->MismatchType;
	}
	/**
	 * @return void
	 * @param MismatchTypeCodeType $value 
	 */
	function setMismatchType($value)
	{
		$this->MismatchType = $value;
	}
	/**
	 * @return dateTime
	 */
	function getActionRequiredBy()
	{
		return $this->ActionRequiredBy;
	}
	/**
	 * @return void
	 * @param dateTime $value 
	 */
	function setActionRequiredBy($value)
	{
		$this->ActionRequiredBy = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('eBayPaymentMismatchDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'MismatchType' =>
					array(
						'required' => false,
						'type' => 'MismatchTypeCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'ActionRequiredBy' =>
					array(
						'required' => false,
						'type' => 'dateTime',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
