<?php
// autogenerated file 10.09.2012 12:58
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that indicates the next possible action that a DE/AT seller can 
 * take toexpedite the seller payout for an order subject to the new eBay payment 
 * process. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RequiredSellerActionCodeType.html
 *
 * @property string ResolveeBPCase
 * @property string MarkAsShipped
 * @property string ContacteBayCS
 * @property string ResolvePPPIcase
 * @property string SetupPayoutMethod
 * @property string UpdatePayoutMethod
 * @property string None
 * @property string CustomCode
 */
class RequiredSellerActionCodeType extends EbatNs_FacetType
{
	const CodeType_ResolveeBPCase = 'ResolveeBPCase';
	const CodeType_MarkAsShipped = 'MarkAsShipped';
	const CodeType_ContacteBayCS = 'ContacteBayCS';
	const CodeType_ResolvePPPIcase = 'ResolvePPPIcase';
	const CodeType_SetupPayoutMethod = 'SetupPayoutMethod';
	const CodeType_UpdatePayoutMethod = 'UpdatePayoutMethod';
	const CodeType_None = 'None';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RequiredSellerActionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RequiredSellerActionCodeType = new RequiredSellerActionCodeType();

?>
