<?php
// autogenerated file 10.09.2012 12:58
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Container for the return preferences of the seller for eBay Returns. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellerReturnPreferencesType.html
 *
 */
class SellerReturnPreferencesType extends EbatNs_ComplexType
{
	/**
	 * @var boolean
	 */
	protected $OptedIn;

	/**
	 * @return boolean
	 */
	function getOptedIn()
	{
		return $this->OptedIn;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setOptedIn($value)
	{
		$this->OptedIn = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellerReturnPreferencesType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'OptedIn' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
